server:
  port: 8080
spring:
  datasource:
    username: root  # 更标准的属性名
    password: 123   # 建议使用环境变量或加密
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.66.169.95:3306/ape-frame?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000