server:
  port: 8080
spring:
  datasource:
    username: root  # 更标准的属性名
    password: 123   # 建议使用环境变量或加密
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://100.66.169.95:3306/ape-frame?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      filters: stat,wall,slf4j  # 添加过滤器配置，启用SQL监控必需
      stat-view-servlet:  #进行配置druid中的监控
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
      filter:     #进行配置sql的拦截器
        stat:
          enabled: true    # 注意这里是enabled而不是enable
          log-slow-sql: true   #开启慢查询的监控
          slow-sql-millis: 2000
        wall:  #SQL防火墙的配置
          enabled: true
        web:
          enabled: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"